### ISSUE TITLE
Problems running server

### ISSUE THREAD

**Issue by docent-net** [kjosk/facebook_client_terminal#1]
Hi,

Just cloned the code, edited js/config.js filling it with app_id and secret (leaving host and port untouched - nothing listening on 127.0.0.1:1337), run `npm update` (libraries downloaded sucesfully) and tried to run `node js/run.js`; unfortunately got this:

```
docent:facebook_client_terminal/ (master✗) $ node js/run.js                                                                                                                                                                        [19:34:58]
Server for facebook login is booting...

/home/docent/tmp/facebook_client_terminal/js/facebookterminal.js:39
        throw error;
              ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
    at Object.<anonymous> (/home/docent/tmp/facebook_client_terminal/js/loginserver.js:49:7)
    at Object.<anonymous> (/home/docent/tmp/facebook_client_terminal/js/loginserver.js:80:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Function.FacebookTerminal.start (/home/docent/tmp/facebook_client_terminal/js/facebookterminal.js:28:9)
    at Object.<anonymous> (/home/docent/tmp/facebook_client_terminal/js/run.js:7:6)
```

Thanks for your help,

**Comment by docent-net** [comment]
Created pull request with the fix for above issue https://github.com/kissrobber/facebook_client_terminal/pull/2
